name: Docker image CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'dev'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      
      -
        name: Checkout code
        uses: actions/checkout@v3

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Check Docker status
        run: sudo systemctl status docker
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build image and push to DockerHub
        uses: docker/build-push-action@v3
        with:
          # relative path to the place where source code with Dockerfile is located
          context: https://github.com/Salome6950/GitHub-Actions.git
          # Note: tags has to be all lower-case
          tags: practice:latest
          push: true
          # build on feature branches, push only on main branch
          #push: ${{ github.ref == 'refs/heads/main' }}
      - 
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }