name: Docker build-push CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'dev'

jobs:
  Build-Push:
    runs-on: ubuntu-latest
    steps:
      
      -
        name: Checkout code
        uses: actions/checkout@v3
      - 
        name: docker docker/login-action
        uses: actions/checkout@v2
        env:
          DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: docker login     
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Build Docker image
        run: docker build . --file Dockerfile --tag sago2021/practice:$(date +%s)
      - 
        name: Docker Push
        run: docker push sago2021/practice